package org.example.code.common;


public enum MQ2MYMessageType {
    UNKNOWN,
    TEMP_OUTLIER,
    TEMP_BAD_READING,
    TEMP_MAX_VALUE,
    TEMP_APPROX_MAX_VALUE,
    TEMP_MIN_VALUE,
    TEMP_APPROX_MIN_VALUE,
    LAB_MOVE_INVALID_CORRIDOR,
    LAB_MOVE_INVALID_CONFIG,
    INVALID_DATA_TEMPERATURE,
    INVALID_DATA_MOVEMENT,
    TEMPERATURE,
    MOVEMENT
}
